[package]
name = "cad-annotations"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Annotation entities, business rules and commands."

[dependencies]
cad-domain.workspace = true
cad-db.workspace = true
cad-geometry.workspace = true
cad-measure.workspace = true
