[package]
name = "app-linux"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "yacr-linux"
path = "src/main.rs"

[target.'cfg(target_os = "linux")'.dependencies]
cad-app.workspace = true
cad-db.workspace = true
cad-domain.workspace = true
cad-platform.workspace = true
cad-ui-slint.workspace = true
cad-render-wgpu.workspace = true
cad-diagnostics.workspace = true
cad-representation.workspace = true
serde_json.workspace = true
slint.workspace = true
ashpd = { version = "0.12.3", default-features = false, features = ["async-std"] }
pollster = "0.4"
