#!/usr/bin/env python3
# generate-icons.py -- rasterise the master app icon into per-platform assets.
#
# Source of truth (committed, never generated):
#   assets/yacr-icon.svg
# Generated (committed so packaging/CI needs no rasteriser at build time):
#   assets/yacr-icon.ico                        multi-resolution Windows icon
#   assets/yacr-icon.icns                       multi-resolution macOS icon
#   assets/icons/yacr-<size>.png                PNG set for Linux hicolor and
#                                               the web manifest
#   apps/app-android/res/mipmap-*/ic_launcher*.png
#                                               Android launcher icon (legacy +
#                                               adaptive-foreground densities)
#   apps/app-android/res/mipmap-anydpi-v26/ic_launcher.xml
#   apps/app-android/res/values/colors.xml     adaptive-icon background colour
#
# Requires `rsvg-convert` (librsvg2-bin) and Pillow:
#   sudo apt-get install -y librsvg2-bin
#   python3 -m pip install --user Pillow
#
# Usage: python3 scripts/generate-icons.py [--check]
#   --check  regenerate into a temp tree and fail if any committed asset
#            differs (CI-friendly drift guard).
import argparse
import pathlib
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
SVG = ROOT / "assets" / "yacr-icon.svg"
ASSETS = ROOT / "assets"
ANDROID_RES = ROOT / "apps" / "app-android" / "res"

PNG_SIZES = [16, 24, 32, 48, 64, 128, 256, 512, 1024]
ICO_SIZES = [16, 24, 32, 48, 64, 128, 256]

# (density qualifier, scale factor). Legacy launcher icon = 48dp, adaptive
# foreground canvas = 108dp with the icon scaled to the 66dp safe zone.
ANDROID_DENSITIES = [("mdpi", 1.0), ("hdpi", 1.5), ("xhdpi", 2.0), ("xxhdpi", 3.0), ("xxxhdpi", 4.0)]
ANDROID_BACKGROUND = "#08151D"

ADAPTIVE_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-icons.py; do not edit by hand. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
"""

COLORS_XML = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-icons.py; do not edit by hand. -->
<resources>
    <color name="ic_launcher_background">{ANDROID_BACKGROUND}</color>
</resources>
"""


def render_pngs(svg: pathlib.Path, outdir: pathlib.Path, sizes):
    pngs = {}
    for size in sizes:
        path = outdir / f"{size}.png"
        subprocess.run(
            ["rsvg-convert", "-w", str(size), "-h", str(size), str(svg), "-o", str(path)],
            check=True,
        )
        pngs[size] = path
    return pngs


def write_text(path: pathlib.Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def build(assets: pathlib.Path, android_res: pathlib.Path):
    """Render every derivative under the given asset / Android-res roots."""
    from PIL import Image

    (assets / "icons").mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        pngs = render_pngs(SVG, pathlib.Path(tmp), PNG_SIZES)
        Image.open(pngs[256]).convert("RGBA").save(
            assets / "yacr-icon.ico", format="ICO", sizes=[(s, s) for s in ICO_SIZES]
        )
        Image.open(pngs[1024]).convert("RGBA").save(assets / "yacr-icon.icns", format="ICNS")
        for size in PNG_SIZES:
            Image.open(pngs[size]).convert("RGBA").save(assets / "icons" / f"yacr-{size}.png")
        master = Image.open(pngs[1024]).convert("RGBA")

    for qualifier, scale in ANDROID_DENSITIES:
        legacy = round(48 * scale)
        legacy_img = master.resize((legacy, legacy), Image.LANCZOS)
        legacy_dir = android_res / f"mipmap-{qualifier}"
        legacy_dir.mkdir(parents=True, exist_ok=True)
        legacy_img.save(legacy_dir / "ic_launcher.png")

        canvas = round(108 * scale)
        glyph = round(66 * scale)
        foreground = Image.new("RGBA", (canvas, canvas), (0, 0, 0, 0))
        foreground.alpha_composite(
            master.resize((glyph, glyph), Image.LANCZOS), ((canvas - glyph) // 2, (canvas - glyph) // 2)
        )
        foreground.save(legacy_dir / "ic_launcher_foreground.png")

    write_text(android_res / "mipmap-anydpi-v26" / "ic_launcher.xml", ADAPTIVE_XML)
    write_text(android_res / "values" / "colors.xml", COLORS_XML)


def committed_paths():
    paths = [ASSETS / "yacr-icon.ico", ASSETS / "yacr-icon.icns"]
    paths += [ASSETS / "icons" / f"yacr-{s}.png" for s in PNG_SIZES]
    for qualifier, _ in ANDROID_DENSITIES:
        paths.append(ANDROID_RES / f"mipmap-{qualifier}" / "ic_launcher.png")
        paths.append(ANDROID_RES / f"mipmap-{qualifier}" / "ic_launcher_foreground.png")
    paths.append(ANDROID_RES / "mipmap-anydpi-v26" / "ic_launcher.xml")
    paths.append(ANDROID_RES / "values" / "colors.xml")
    return paths


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not SVG.is_file():
        print(f"missing source icon: {SVG}", file=sys.stderr)
        return 1
    if subprocess.run(["which", "rsvg-convert"], capture_output=True).returncode != 0:
        print("rsvg-convert not found; install librsvg2-bin", file=sys.stderr)
        return 1

    if not args.check:
        build(ASSETS, ANDROID_RES)
        for path in committed_paths():
            print(f"{path.relative_to(ROOT)}  {path.stat().st_size} bytes")
        return 0

    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        build(tmp / "assets", tmp / "apps" / "app-android" / "res")
        drift = []
        for path in committed_paths():
            fresh = tmp / path.relative_to(ROOT)
            if not path.is_file() or path.read_bytes() != fresh.read_bytes():
                drift.append(str(path.relative_to(ROOT)))
        if drift:
            print("icon assets out of date: " + ", ".join(drift), file=sys.stderr)
            return 1
        print("icon assets up to date")
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
