[package]
name = "cad-scene"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Chunking, batching, LOD, display caches and update sets."

[dependencies]
cad-domain.workspace = true
cad-db.workspace = true
cad-geometry.workspace = true
cad-representation.workspace = true
cad-spatial.workspace = true
cad-dependencies.workspace = true
